### ISSUE TITLE
How to specify region?

### ISSUE THREAD

**Issue by caddac** [boltops-tools/lono#1]
Hi, I'm considering using lono for managing our CF templates. I'm wondering how does lono use/specify region? 

For instance, would I deploy a given stack to us-east-1 vs us-west-2?

**Comment by tongueroo** [comment]
Usually do it with the ~/.aws/config and `AWS_PROFILE` https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

You can also override the region with `AWS_REGION`
