### ISSUE TITLE
lono blueprint new demo not creating config files

### ISSUE THREAD

**Issue by atehac** [boltops-tools/lono#73]
lono not creating starter config as per this guide -- https://blog.boltops.com/2019/10/30/lono-cloudformation-framework-introduction-series-part-1-ec2-instance

for example:
      

> create  configs/demo/params/development.txt
>       create  configs/demo/params/production.txt
>       create  configs/demo/variables/development.rb
>       create  configs/demo/variables/production.rb

https://gist.github.com/atehac/fe75cbf9427c138fc9339cd2915e6cb8

**Comment by tongueroo** [comment]
no longer version with the next version of lono, in prerelease now
